- hosts: "managed_node"
  tasks:
  - name: "Yum Repo"
    yum_repository:
      name: "docker"
      description: "docker softwares"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
      gpgcheck: "no"
  
  - name: "Install Docker"
    package:
      name: "docker-ce-18.09.1-3.e17.x86_64"
      state: present

  - name: "Start Docker Service"
    service:
      name: "docker"
      state: started
      enabled: yes

  - name: "Docker SDK in Python"
    command: "pip3 install docker"

  - name: "Directory to store html file"
    file:
      path: "/mydocs"
      state: directory

  - name: "Copying html file"
    copy:
      src: "index.html"
      dest: "/mydocs"

  - name: "Creating Container with httpd webserver"
    docker_container:
      name: "myweb"
      image: "httpd"
      state: started
      exposed_ports: "80"
      ports: "7755:80"
      volumes:
      - /mydocs:/usr/local/apache2/htdocs/
